version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.86.1
    ports:
      - "5679:5678"  # <-- Fix: needs to map host:container
    restart: always
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://${N8N_HOST}:${N8N_PORT}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_prod_data:/home/node/.n8n

volumes:
  n8n_prod_data:
